#!/bin/bash
# chkconfig: 2345 20 80
# description: ngEO-QS service
# @purpose NGEO service script. To be placed in /etc/init.d
# MAKE SURE to change the [IPADRESS] by the ip adress of the machine where are you installing this ngEO-QS.
# If you have deploied ngEO-QS using rpm , then the ngeo is placed @ /usr/local/ngeo/ngeo-qs/
# If you have installed it in another place then change the path by where it is installed
# IF YOU WANT TO CHANGE THE PORT, THEN CHANGE IT HERE

. /etc/init.d/functions

case "$1" in
start)
   #check if always running the mode process
   NODEPID=$(ps -ef | grep '\snode\s' | awk '{print $2}')
   #If the process is still running, then kill it, but normally the step just before should have killed it
   #This is the way to stop node because nothing exists apart this actually
   if [[ ! -z ${NODEPID} ]]
   then
     kill ${NODEPID}
   fi
   cd /usr/local/ngeo/ngeo-qs/
   #mongo admin --eval 'db.shutdownServer()' > /dev/null
   mongod --config ./.mongodb/conf/mongod.conf --fork
   #PROTOCOL could be 'BOTH' if you want to start qs on both http and https protocol, or 'HTTP' for only http protocol or 'HTTPS' for only https protocol or if other values or not set then will be considered as 'BOTH'
   NODE_ENV=production HOST=[IPADRESS] HTTP_PORT=8080 HTTPS_PORT=443 PROTOCOL=BOTH node src/app.js &
   echo $!>/var/run/ngEO-QS.pid
   echo "ngEO-QS started"
   ;;
stop)
   cd /usr/local/ngeo/ngeo-qs/
   mongo admin --eval 'db.shutdownServer()' > /dev/null
   kill `cat /var/run/ngEO-QS.pid`
   #check if always running the mode process
   NODEPID=$(ps -ef | grep '\snode\s' | awk '{print $2}')
   #If the process is still running, then kill it, but normally the step just before should have killed it
   #This is the way to stop node because nothing exists apart this actually
   if [[ ! -z ${NODEPID} ]]
   then
     kill ${NODEPID}
   fi
   #ps -ef | grep '\snode\s' | awk '{print $2}' | xargs kill
   rm /var/run/ngEO-QS.pid
   echo "ngEO-QS stoppped"
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/ngEO-QS.pid ]; then
      echo ngEO-QS is running, pid=`cat /var/run/ngEO-QS.pid`
   else
      echo ngEO-QS is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
